services:
  mongodb:
    image: mongo:8.2.3
    container_name: compass-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"

    volumes:
      - compass-mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: compass
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

volumes:
  compass-mongo-data:
    external: true